### PR TITLE
give new names to move IAM roles, make sqs pocily deploy first

### PR DESCRIPTION
**Pull request by stevensnicholas**
https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/

### CODE REVIEW

**Comment by The-TT-Hacker** [comment]
@stevensnicholas does this deploy against aws when you run the terraform locally?

**Comment by stevensnicholas** [comment]
> @stevensnicholas does this deploy against aws when you run the terraform locally?

We will have to add the deplment name var into ecr first. I'v made another PR for that https://github.com/stevensnicholas/comp9447-team2/pull/125

**Comment by stevensnicholas** [comment]
We first need to get the build action working before we can change over to the named ecr which will allow us deploy from terraform locally to aws without naming issues. There are also the circular loop of the lambda being depended on a image in a ecr that is created at the same time.

**Comment by thefishua** [comment]
Is this fixed and ready to be pushed, it seems fine just hesitant because of your comment above

**Comment by stevensnicholas** [comment]
Yes this one needs to be merged first

**Review by thefishua — APPROVED** [review]
LGTM

**Pull request merged**
