### PR TITLE
add back in restler

### PR DESCRIPTION
**Pull request by stevensnicholas**
When doing local test if you don't have any images in your own ecr, use one from main-
117712065617.dkr.ecr.ap-southeast-2.amazonaws.com/main_dyno_image_repository:9270505710dab7540a8340efc24fef311b75552e

### CODE REVIEW

**Comment by thefishua** [comment]
Are you able to prompt the user to use this ?

**Comment by stevensnicholas** [comment]
I'v altered it to have ECR in its own module. That way for the demo in a new account we deploy that first, the everything else.
I have updated the md files to reflect as such

**Comment by thefishua** [comment]
I see you made a gitignore in the terraform folder should that be in the gitignore in the main dir

**Comment by thefishua** [comment]
Too many errors that would break the pipeline

**Pull request closed without merging**
