### PR TITLE
give local its own module that will allow localstack to run

### PR DESCRIPTION
**Pull request by stevensnicholas**

### CODE REVIEW

**Comment by The-TT-Hacker** [comment]
You dont need to have a complete separate copy of everything, you can use terraform modules to import large blocks of terraform code https://www.terraform.io/language/modules/syntax

**Comment by The-TT-Hacker** [comment]
Basically just delete all the stuff in the terraform/aws directory thats already in the terraform/local directory. then use the "module" terraform block to import both the terraform/aws module and the terraform/local module into the top level module (the terraform directory). Then for local deployments you can execute terraform from the terraform/local directory and for production execute terraform from the terraform directory.

This way you have no duplicate code.

**Comment by stevensnicholas** [comment]
@The-TT-Hacker I have removed the duplication and at the root directory it will now call first the main module then the aws_only one. There is instruction on how to run locally in the main directory

**Comment by thefishua** [comment]
Looks good to me

**Pull request merged**
