### PR TITLE
Add localstack and add count to non free resources

### PR DESCRIPTION
**Pull request by stevensnicholas**

### CODE REVIEW

**Comment by MrC1rcle** [comment]
what does count do here

**Comment by vsn-hub** [comment]
> what does count do here

same not exactly sure

**Comment by The-TT-Hacker** [comment]
I would split it up into 2 terraform modules (2 directories in the terraform directory each with their own variables and outputs).
One for the the golang API which needs localstack pro, and one for everything else.
This way you can just run the terraform for localstack separately to the API gateway

**Comment by stevensnicholas** [comment]
Closed it is replced by https://github.com/stevensnicholas/comp9447-team2/compare/main...localstack-2 which separates the local and aws stacks into separate modules

**Pull request closed without merging**
