### PR TITLE
Implementation of AWS for issues section

### PR DESCRIPTION
**Pull request by thefishua**
Terraform code for aws for deploying issues

### CODE REVIEW

**Comment by thefishua** [comment]
Still need to add the lambda functionality in the handler

**Comment by The-TT-Hacker** [comment]
@thefishua rebase main onto this branch and resolve the conflicts

**Comment by thefishua** [comment]
What exactly is the command for rebasing the branch with main
I tried git rebase --onto main aws-issues, but failed

**Comment by thefishua** [comment]
I'm closing this branch as there are too many file changes

**Pull request closed without merging**
