### PR TITLE
get token demo

### PR DESCRIPTION
**Pull request by MrC1rcle**
test function of getting the github oauth token

### CODE REVIEW

**Comment by vsn-hub** [comment]
looks good so is this working at the moment?

**Comment by MrC1rcle** [comment]
> looks good so is this working at the moment?
I just found there is a problem. I'll fix it

**Comment by MrC1rcle** [comment]
now it works and can get the token

**Comment by The-TT-Hacker** [comment]
this demo is all well and good but theres no reason for this to be merged in, it needs to be integrated with the actual backend

**Comment by MrC1rcle** [comment]
ok I'll integrate this

**Pull request closed without merging**
