### PR TITLE
Updated Diagram with current backend layout

### PR DESCRIPTION
**Pull request by thefishua**
Added the backend architecture to the diagram that was described by Tim with some small changes.

### CODE REVIEW

**Comment by The-TT-Hacker** [comment]
Can you export a PNG and store that in the repo as well?

**Comment by thefishua** [comment]
> Can you export a PNG and store that in the repo as well?

Added the PNG file and placed it in the README should be good to merge now

**Comment by The-TT-Hacker** [comment]
Make sure everyone reviews this before its merged so everyones on the same page

**Comment by thefishua** [comment]
> Make sure everyone reviews this before its merged so everyones on the same page

We have a meeting tonight so I'll push people to be more active on the github

**Comment by Twdckcv** [comment]
As discussed yesterday, since the website will get the fuzzing data from dynodb, should we have an arrow pointing from 
the db to the website for clearer understanding?

**Pull request merged**
